import { demoNotice, trucks, routes, sectors, drivers, incidents, notifications, municipalities, routeFlow } from '../shared/demo-data.js';

const $ = (selector) => document.querySelector(selector);
const app = $('#app');
const driverName = (id) => drivers.find((driver) => driver.id === id)?.name ?? 'Sin asignar';
const routeName = (id) => routes.find((route) => route.id === id)?.name ?? 'Sin ruta';

function progress(value) { return `<div class="progress"><i style="width:${value}%"></i></div>`; }
function pill(state) { return `<span class="pill ${state}">${state}</span>`; }

function renderMap() {
  const streets = Array.from({ length: 10 }, (_, index) => `<i class="street" style="left:${8 + index * 8}%;top:${18 + (index % 5) * 14}%;width:34%;transform:rotate(${index % 2 ? -12 : 18}deg)"></i>`).join('');
  const routeLines = routes.map((route, index) => `<i class="route" style="left:${18 + index * 12}%;top:${28 + index * 12}%;width:${28 + index * 4}%;transform:rotate(${index % 2 ? 28 : -16}deg)"></i>`).join('');
  const truckMarkers = trucks.map((truck) => `<button class="truck ${truck.state}" data-truck="${truck.id}" style="left:${truck.lat}%;top:${truck.lng}%" title="${truck.name}">🚛</button>`).join('');
  const sectorMarkers = sectors.map((sector, index) => `<span class="marker" style="left:${22 + index * 18}%;top:${18 + index * 16}%">${sector.name}</span>`).join('');
  return `<section id="mapa" class="hero"><div class="card"><h1>Mapa operativo local</h1><p class="demo">${demoNotice}</p><div class="map">${streets}${routeLines}${sectorMarkers}${truckMarkers}</div></div><aside class="card" id="detail"><h2>Detalle operativo</h2>${renderTruckDetail(trucks[0])}</aside></section>`;
}
function renderTruckDetail(truck) { return `<div class="list"><div class="row"><strong>${truck.name}</strong>${pill(truck.state)}</div><p>Ruta: ${routeName(truck.routeId)}</p><p>Conductor: ${driverName(truck.driverId)}</p><p>Sector: ${truck.sector}</p>${progress(truck.progress)}<p><strong>${truck.progress}%</strong> de avance</p><h3>Timeline</h3><div class="timeline">${routeFlow.map((step) => `<p>${step === 'delayed' && truck.state !== 'delayed' ? '○' : '●'} ${step}</p>`).join('')}</div>${truck.state === 'delayed' ? '<div class="card alert">Alerta por retraso: revisar tráfico y reasignación.</div>' : ''}</div>`; }
function renderMunicipal() { return `<section id="municipal" class="section card"><h2>Panel municipal</h2><p class="demo">${demoNotice}</p><div class="kpis"><div class="kpi"><strong>86%</strong><br>Cumplimiento</div><div class="kpi"><strong>3</strong><br>Camiones activos</div><div class="kpi"><strong>1</strong><br>Retrasos</div><div class="kpi"><strong>${incidents.length}</strong><br>Incidencias</div></div><div class="controls"><input id="search" placeholder="Buscar ruta, camión o sector"><select id="sectorFilter"><option value="">Todos los sectores</option>${sectors.map((s) => `<option>${s.name}</option>`).join('')}</select></div><div class="panel-grid"><div><h3>Rutas del día</h3><div class="list" id="routeList">${renderRoutes(routes)}</div></div><div><h3>Asignación visual</h3>${routes.map((route) => `<div class="row"><span>${route.name}</span><span>🚛 ${route.truckId} · ${driverName(route.driverId)}</span></div>`).join('')}</div><div><h3>Vista supervisor</h3>${incidents.map((incident) => `<div class="row"><span>${incident.id}<br>${incident.type}</span>${pill(incident.status.toLowerCase().replaceAll(' ', '-'))}</div>`).join('')}</div></div><h3>Vista móvil conductor</h3><div class="mobile"><h4>Ruta asignada</h4><p>Ruta Centro AM → En progreso</p><button data-flow>Avanzar flujo demo</button><p id="flowState">planned</p></div></section>`; }
function renderRoutes(items) { return items.map((route) => `<article class="row"><div><strong>${route.name}</strong><br>${route.sector} · ETA ${route.eta}<br>${progress(route.progress)}</div><div>${pill(route.status)}<br>${route.covered}/${route.stops} paradas</div></article>`).join(''); }
function renderCitizen() { return `<section id="ciudadania" class="section card"><h2>Portal ciudadano</h2><p class="demo">${demoNotice}</p><div class="panel-grid"><div><h3>Consulta de recogida</h3><select id="citizenSector">${sectors.map((s) => `<option value="${s.id}">${s.name}</option>`).join('')}</select><p id="pickupResult"></p><h3>Avisos municipales</h3>${notifications.map((n) => `<div class="row">🔔 ${n}</div>`).join('')}</div><form id="incidentForm"><h3>Reportar incidencia</h3><select name="type"><option>Basura no recogida</option><option>Vertedero improvisado</option></select><textarea name="description" placeholder="Descripción demo"></textarea><input type="file" aria-label="Adjuntar evidencia demo"><button>Obtener folio</button><p id="folio"></p></form><div><h3>Consultar estado</h3><input id="folioSearch" value="SW-FOLIO-1001"><button id="checkFolio">Consultar</button><p id="folioStatus"></p><h3>Futura relación</h3><p>Preparado para Chatbot Municipal: preguntas frecuentes, folios y avisos por sector.</p></div></div></section>`; }
function renderMaster() { return `<section id="master" class="section card"><h2>Master Admin MT IT Services</h2><p class="demo">${demoNotice}</p><div class="panel-grid">${municipalities.map((m) => `<article class="card"><h3>${m.name}</h3><p>Plan: ${m.plan}</p><p>Camiones: ${m.trucks} · Rutas: ${m.routes} · Usuarios: ${m.users}</p>${pill(m.status.toLowerCase())}<button>Onboarding demo</button></article>`).join('')}</div><h3>Métricas agregadas</h3><div class="kpis"><div><strong>2</strong><br>Municipios</div><div><strong>17</strong><br>Camiones</div><div><strong>25</strong><br>Rutas</div><div><strong>3</strong><br>Alertas</div></div></section>`; }

app.innerHTML = `${renderMap()}${renderMunicipal()}${renderCitizen()}${renderMaster()}`;
document.addEventListener('click', (event) => {
  const truckButton = event.target.closest('[data-truck]');
  if (truckButton) $('#detail').innerHTML = `<h2>Detalle operativo</h2>${renderTruckDetail(trucks.find((truck) => truck.id === truckButton.dataset.truck))}`;
  if (event.target.matches('[data-flow]')) { const current = $('#flowState').textContent; $('#flowState').textContent = routeFlow[(routeFlow.indexOf(current) + 1) % routeFlow.length]; }
  if (event.target.id === 'checkFolio') { const found = incidents.find((incident) => incident.id === $('#folioSearch').value); $('#folioStatus').textContent = found ? `${found.type}: ${found.status}` : 'Folio demo no encontrado'; }
});
$('#search').addEventListener('input', (event) => { const term = event.target.value.toLowerCase(); $('#routeList').innerHTML = renderRoutes(routes.filter((route) => JSON.stringify(route).toLowerCase().includes(term))); });
$('#sectorFilter').addEventListener('change', (event) => { $('#routeList').innerHTML = renderRoutes(routes.filter((route) => !event.target.value || route.sector === event.target.value)); });
$('#citizenSector').addEventListener('change', (event) => { const sector = sectors.find((item) => item.id === event.target.value); $('#pickupResult').textContent = `${sector.pickupDay} · Estado: ${sector.status}`; });
$('#citizenSector').dispatchEvent(new Event('change'));
$('#incidentForm').addEventListener('submit', (event) => { event.preventDefault(); $('#folio').textContent = `Folio generado: SW-FOLIO-${Math.floor(2000 + Math.random() * 7000)} (demo)`; });
