import { cpSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildSync } from 'esbuild';

const mobileDir = dirname(dirname(fileURLToPath(import.meta.url)));
const repositoryDir = dirname(mobileDir);
const frontendDir = join(repositoryDir, 'frontend');
const sharedDir = join(repositoryDir, 'shared');
const outputDir = join(mobileDir, 'www');
const outputSharedDir = join(outputDir, 'shared');
const indexPath = join(outputDir, 'index.html');
const nativeEntryPath = join(mobileDir, 'src', 'native-background-geolocation.js');
const configStart = '<!-- SMARTWASTE_SUPABASE_CONFIG:START (generated by mobile/scripts/build-web.mjs) -->';
const configEnd = '<!-- SMARTWASTE_SUPABASE_CONFIG:END -->';

function stripGeneratedConfig(html) {
  const start = html.indexOf('<!-- SMARTWASTE_SUPABASE_CONFIG:START');
  if (start === -1) return html;
  const end = html.indexOf(configEnd, start);
  if (end === -1) return html;
  return html.slice(0, start) + html.slice(end + configEnd.length).replace(/^\r?\n/, '');
}

function injectSupabaseConfig() {
  const url = process.env.SUPABASE_URL;
  const anonKey = process.env.SUPABASE_ANON_KEY;

  if (!url && !anonKey) {
    console.warn('SUPABASE_URL/SUPABASE_ANON_KEY absent: mobile bundle built in demo mode.');
  } else if (!url || !anonKey) {
    throw new Error('SUPABASE_URL and SUPABASE_ANON_KEY must be provided together.');
  }

  const config = url && anonKey ? {
    url,
    anonKey,
    municipality_id: process.env.SUPABASE_MUNICIPALITY_ID || null,
    hideDemo: process.env.SUPABASE_HIDE_DEMO === 'true'
  } : null;
  const configScript = config ? `  <script>\n    window.SMARTWASTE_SUPABASE_CONFIG = ${JSON.stringify(config)};\n  </script>\n` : '';
  const block = `${configStart}\n${configScript}  <script src="./native-background-geolocation.js"></script>\n  ${configEnd}\n`;
  const html = stripGeneratedConfig(readFileSync(indexPath, 'utf8'));
  const scriptTag = '<script type="module" src="./app.js"></script>';
  if (!html.includes(scriptTag)) throw new Error(`Expected ${scriptTag} in copied frontend/index.html.`);
  writeFileSync(indexPath, html.replace(scriptTag, `${block}  ${scriptTag}`));
}

rmSync(outputDir, { recursive: true, force: true });
mkdirSync(outputDir, { recursive: true });
cpSync(frontendDir, outputDir, { recursive: true });
cpSync(sharedDir, outputSharedDir, { recursive: true });

buildSync({ entryPoints: [nativeEntryPath], bundle: true, outfile: join(outputDir, 'native-background-geolocation.js'), format: 'iife', platform: 'browser' });

for (const entry of readdirSync(outputDir, { withFileTypes: true })) {
  if (!entry.isFile() || !entry.name.endsWith('.js')) continue;
  const path = join(outputDir, entry.name);
  const source = readFileSync(path, 'utf8');
  writeFileSync(path, source.replaceAll('../shared/', './shared/'));
}

injectSupabaseConfig();
console.log(`Mobile web bundle generated at ${outputDir}.`);
