-- SmartWaste SW-007 local draft migration. Not applied remotely.
create table if not exists municipalities (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, country text not null default 'República Dominicana', status text not null default 'onboarding', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists municipality_settings (id uuid primary key default gen_random_uuid(), municipality_id uuid not null references municipalities(id), settings jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists profiles (id uuid primary key, display_name text not null, email text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists memberships (id uuid primary key default gen_random_uuid(), municipality_id uuid not null references municipalities(id), profile_id uuid not null references profiles(id), role text not null, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(municipality_id, profile_id));
create table if not exists vehicles (id uuid primary key default gen_random_uuid(), municipality_id uuid not null references municipalities(id), code text not null, plate text, state text not null default 'offline', created_by uuid references profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(municipality_id, code));
create table if not exists drivers (id uuid primary key default gen_random_uuid(), municipality_id uuid not null references municipalities(id), profile_id uuid references profiles(id), display_name text not null, status text not null default 'available', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists sectors (id uuid primary key default gen_random_uuid(), municipality_id uuid not null references municipalities(id), name text not null, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists routes (id uuid primary key default gen_random_uuid(), municipality_id uuid not null references municipalities(id), name text not null, status text not null default 'planned', created_by uuid references profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists route_stops (id uuid primary key default gen_random_uuid(), municipality_id uuid not null references municipalities(id), route_id uuid not null references routes(id), sequence int not null, label text not null, latitude numeric, longitude numeric, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists route_runs (id uuid primary key default gen_random_uuid(), municipality_id uuid not null references municipalities(id), route_id uuid not null references routes(id), vehicle_id uuid references vehicles(id), driver_id uuid references drivers(id), status text not null default 'planned', correlation_id uuid not null default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists vehicle_assignments (id uuid primary key default gen_random_uuid(), municipality_id uuid not null references municipalities(id), vehicle_id uuid not null references vehicles(id), driver_id uuid references drivers(id), route_run_id uuid references route_runs(id), status text not null default 'assigned', created_by uuid references profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists vehicle_positions (id uuid primary key default gen_random_uuid(), municipality_id uuid not null references municipalities(id), vehicle_id uuid not null references vehicles(id), latitude numeric not null, longitude numeric not null, accuracy numeric, speed numeric, heading numeric, captured_at timestamptz not null, received_at timestamptz not null default now(), source text not null, device_id text, correlation_id uuid not null default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists incidents (id uuid primary key default gen_random_uuid(), municipality_id uuid not null references municipalities(id), route_run_id uuid references route_runs(id), vehicle_id uuid references vehicles(id), type text not null, status text not null default 'open', priority text not null default 'medium', description text, correlation_id uuid not null default gen_random_uuid(), created_by uuid references profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists citizen_reports (id uuid primary key default gen_random_uuid(), municipality_id uuid not null references municipalities(id), sector_id uuid references sectors(id), folio text not null, type text not null, status text not null default 'received', channel text not null default 'web', description text, evidence_path text, correlation_id uuid not null default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(municipality_id, folio));
create table if not exists audit_events (id uuid primary key default gen_random_uuid(), municipality_id uuid references municipalities(id), actor_profile_id uuid references profiles(id), action text not null, entity_type text not null, entity_id uuid, payload jsonb not null default '{}', correlation_id uuid default gen_random_uuid(), created_at timestamptz not null default now());
create table if not exists integration_events (id uuid primary key default gen_random_uuid(), municipality_id uuid references municipalities(id), integration text not null, status text not null, payload jsonb not null default '{}', correlation_id uuid default gen_random_uuid(), created_at timestamptz not null default now());
